#!/bin/bash
# $Id: ci 35.480.he6bvF6LXPCcviw5/YCTAlC5AbA 2007-01-25 07:23:22 -0500 $
# vi:syntax=gentoo-init-d:

source /sbin/functions.sh
set -e; trap "eend 997" ERR

figlet 'Checking IN'

ebegin "pulling/merging updates"
cg update
eend $?

ebegin "rcskeywords -m"
rcskeywords -m
eend $?

ebegin "updating update index (cache)"
(git-update-index --refresh >/dev/null)
einfo "(updated)";
eend $?

ebegin "committing changes"
if [ -z "$*" ]; then
    cg commit

else 
    cg commit -m "$*"
fi
eend $?

ebegin "pushing commit to repo"
cg push
eend $?

