#!/bin/bash
# vi:syntax=gentoo-init-d:

source /sbin/functions.sh
set -e; trap "eend 997" ERR

ebegin "checking MANIFEST";
./distclean
eend $?

ebegin "checking status"
set -x
cg update
cg status
set +x
eend $?

ebegin "checking in"
set -x
cg commit -m "$0"
cg push
set +x
echo "check in complete"
eend $?
