#!/bin/sh

./ci

p=Changes
pack=PBC.pm

perl -i -pe 's/(\$VERSION[^0-9]+[0-9.-]+)([0-9]+\.[0-9]+)([^0-9]+)/$1 . sprintf("\%0.2f", $2+0.01)  . $3/e;' $pack | grep VERS
v=`perl -ne 'print "$1\n" if m/\\$VERSION[^0-9]+([0-9.]+)\b/' $pack`

if [ -f $p ]; then
    mv $p $p.bak
    echo -n $v:'  '       > $p
    date                 >> $p
    echo "   - $USER $*" >> $p
    echo                 >> $p
    cat $p.bak           >> $p
    rm $p.bak
    vi $p -c "set tw=800" -s format.scr
    clear
    head -n 20 $p
fi

cvs ci -m logged
