#!/usr/bin/perl
# vi:tw=0:

# load this test version, not the installed version:
BEGIN { system('perl Makefile.PL') unless -f 'Makefile'; system("make"); unshift @INC, 'blib/arch', 'blib/lib' }

use strict;
use Crypt::PBC;

my $curve = new Crypt::PBC("params_a.txt");
my $Zr    = $curve->init_Zr->random;
my $G1    = $curve->init_G1->random;
my $G2    = $curve->init_G2->random;
my $GT    = $curve->init_GT->random;

print "$G1:\n"; $G1->stddump; print "\no: ", &Crypt::PBC::element_order($G1), "\n\n";
print "$G2:\n"; $G2->stddump; print "\no: ", &Crypt::PBC::element_order($G2), "\n\n";

$G1->double($G2);
