#!/usr/bin/perl
# vi:tw=0:

# load this test version, not the installed version:
BEGIN { system('perl Makefile.PL && make') unless -d 'blib/arch' and -d 'blib/lib'; unshift @INC, 'blib/arch', 'blib/lib' }

use strict;
use Crypt::PBC;

my $curve = new Crypt::PBC("params_e.txt");
my $Zr    = $curve->init_Zr->random;
my $G1    = $curve->init_G1->random;
my $G2    = $curve->init_G2->random;
my $GT    = $curve->init_GT->random;

my $s   = $curve->init_Zr->random;
my $Q_i = $curve->init_G1->set_to_hash("fuckah!");
my $d_i = $curve->init_G2->pow_zn( $Q_i, $s );
